version: "3"
services:
  file-validation:
    image: 247222723249.dkr.ecr.eu-west-2.amazonaws.com/tdr
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_COGNITO_CLIENT_ID
        - AWS_COGNITO_CLIENT_SECRET
    container_name: file-validation
  clamav:
    image: 247222723249.dkr.ecr.eu-west-2.amazonaws.com/clamav
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
      dockerfile: Dockerfile-clamav
    ports:
      - 3310:3310
    container_name: clamav
  siegfried:
    image: 247222723249.dkr.ecr.eu-west-2.amazonaws.com/siegfried
    build:
      context: .
      dockerfile: Dockerfile-siegfried
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    ports:
      - 5138:5138
    container_name: siegfried
