FROM ubuntu
RUN apt-get update \
                && apt-get install -y wget gnupg2 \
                && wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | apt-key add - \
                && echo "deb http://dl.bintray.com/siegfried/debian wheezy main" | tee -a /etc/apt/sources.list \
                && apt-get update \
                && apt-get install -y siegfried
CMD sf -log e,w,u,o -serve 0.0.0.0:5138